### ISSUE TITLE
HTML5 Geolocation 

### ISSUE THREAD

**Issue by doanerock** [jackspirou/clientjs#67]
Are there any plans to add HTML5 Geolocation to the list of methods?

**Comment by BendingBender** [comment]
I don't see how this could be useful without using a proprietary reverse geocoding service. And even if this was easily doable, the idea is to produce a stable fingerprint but nowadays most devices with a browser are portable, this would make the hash change on any location change.

Closing this due to age, feel free to reopen if you want to discuss this further.
